version: '3.1'

services:
  app:
    image: 'be3eb3d8'
    container_name: app
    ports:
      - '8080:8080'
    environment:
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=admin"
      - "DB_URL=jdbc:mysql://db:3306/employees_db"
    depends_on:
      - db
  db:
    image: "mysql"
    container_name: db
    ports:
      - '3306:3306'
    environment:
      - "MYSQL_ROOT_USER=admin"
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_DATABASE=employees_db"